#include <iostream>
#include <dirent.h>
#include <string.h>
#include <vector>
#include <fstream>
#include <chrono>
#include <ctime>

using namespace std;

bool hasExtension(const char* file, const char* ext) {
    char extGet[10];
    bool dotFound = false;
    int c = 0;
    for (int i = 0; i < (int)strlen(file); i++) {
        if (dotFound) {
            extGet[c] = file[i];
            c++;
        }
        if (file[i] == '.') dotFound = true;
    }
    extGet[c] = '\0';
    bool result = false;
    if (dotFound) {
        if (strcmp(extGet, ext) == 0) {
            result = true;
        }
    }
    return result;
}

void getFilesToCompile(const char* path, vector<string> &sources, vector<string> &headers) {
    if (auto dir = opendir(path)) {
        while (auto f = readdir(dir)) {
            if (!f->d_name) continue;
            char path1[1000];
            strcpy(path1, path);
            strcat(path1, "\\");
            strcat(path1, f->d_name);
            if (opendir(path1)) {
                //cout << "Directory: " << f->d_name << endl;
                if (strcmp(f->d_name, ".") != 0 && strcmp(f->d_name, "..") != 0) {
                    //cout << "List of files in: " << f->d_name << endl;
                    getFilesToCompile(path1, sources, headers);
                }
            } else {
                //cout << "File: " << path << endl;
                string result = "";
                if (hasExtension(f->d_name, "cpp")) {
                    for (char c : f->d_name) {
                        if (c == '.') break;
                        result.push_back(c);
                    }
                    sources.push_back(result);
                } else if (hasExtension(f->d_name, "h") || hasExtension(f->d_name, "hpp")) {
                    for (char c : f->d_name) {
                        if (c == '.') break;
                        result.push_back(c);
                    }
                    headers.push_back(result);
                }
            }
        }
        closedir(dir);
    }
}

int main(int argc, char **argv) {
    string includeDir, srcDir, buildDir, outputDir, output, CC, CFLAGS, path = ".";
	vector<string> sources, headers, classes;
    getFilesToCompile(path.c_str(), sources, headers);
    for (string src : sources) {
        for (string h : headers) {
            if (src == h) {
                classes.push_back(src);
                break;
            }
        }
    }
    
    for (string str : classes) {
        cout << str << endl;
    }

	includeDir = "include";
    srcDir = "src";
	buildDir = "obj";
	outputDir = "bin";
	output = "App.exe";
	CC = "g++";
	CFLAGS = "-std=c++11 -Wall -Weffc++ -pedantic";

    time_t time = chrono::system_clock::to_time_t(chrono::system_clock::now());
    ofstream f("Makefile");
    f << "# Makefile generated by AutoMakefile at " << ctime(&time) << "\n"
      << "CC := " << CC
      << "\n\nSRCDIR := " << srcDir
      << "\nINCDIR := " << includeDir
      << "\nBUILDDIR := " << buildDir
      << "\nOUTPUTDIR := " << outputDir
      << "\n\nTARGET := $(OUTPUTDIR)\\" << output
      << "\nCFLAGS := " << CFLAGS
      << "\n\nall: $(TARGET)"
      << "\n\n$(TARGET): $(BUILDDIR)\\main.o";
    if (classes.size() > 0) {
        f << "$(BUILDDIR)\\";
        for (int i = 0; i < classes.size(); i++) {
            f << classes[i] << (i < classes.size()-1 ? ".o $(BUILDDIR)\\" : ".o\n");
        }
    } else f << "\n";
    f << "\t$(CC) $(CFLAGS) $^ -o $(TARGET)\n\n"
      << "$(BUILDDIR)\\main.o: main.cpp\n"
      << "\t$(CC) -c main.cpp -o $(BUILDDIR)\\main.o\n\n";
    for (string str : classes) {
        f << "$(BUILDDIR)\\" << str <<".o: $(SRCDIR)\\" << str << ".cpp $(INCDIR)\\" << str << ".h\n"
          << "\t$(CC) -c $(SRCDIR)\\" << str << ".cpp -o $(BUILDDIR)\\" << str << ".o\n\n";
    }

    f << "clean:\n"
	<< "\t@erase $(BUILDDIR)\\*.o\n"
	<< "\t@erase $(TARGET)\n";
    f.close();
	return 0;
}
