# Makefile generated by AutoMakefile at Tue Oct 05 10:31:01 2021

CC := g++

SRCDIR := src
INCDIR := include
BUILDDIR := obj
OUTPUTDIR := bin

TARGET := $(OUTPUTDIR)\App.exe
CFLAGS := -std=c++11 -Wall -Weffc++ -pedantic

all: $(TARGET)

$(TARGET): $(BUILDDIR)\main.o
	$(CC) $(CFLAGS) $^ -o $(TARGET)

$(BUILDDIR)\main.o: main.cpp
	$(CC) -c main.cpp -o $(BUILDDIR)\main.o

clean:
	@erase $(BUILDDIR)\*.o
	@erase $(TARGET)
